### ISSUE TITLE
Ubuntu base images don't work on Raspberry Pi Zero

### ISSUE THREAD

**Issue by bauerj** [home-assistant/hassio-base#6]
The Alpine-based images work fine on my Raspberry Pi Zero:
```
# docker run -it "homeassistant/armhf-base" uname -arr
Linux 2ba42942fe33 4.14.81 #1 Sun Feb 3 21:00:44 UTC 2019 armv6l Linux
```

However, the Ubuntu-based images do not:
```
# docker run -it "homeassistant/armhf-base-ubuntu" uname -arr
# echo $?
139
```

Exit code 139 means the process has received signal 139-128=11 (`SIGSEV`). I wasn't able to debug this further but I assume this is because the BCM2835 SoC on the Pi Zero only supports the ARMv6 instruction set.

Is the Ubuntu image intentionally compiled with the ARMv7 instruction set?

**Comment by bauerj** [comment]
I assume this could be changed here: https://github.com/home-assistant/hassio-base/blob/master/ubuntu/armhf/Dockerfile#L2 (compared to https://github.com/home-assistant/hassio-base/blob/master/alpine/armhf/Dockerfile#L2)

**Comment by frenck** [comment]
@bauerj This will never work.

Raspberry Pi Zero is an ARM v6 based device.
Ubuntu does not ship for ARM v6, only for ARM v7 and higher.

**Comment by bauerj** [comment]
I see. Could Hass.io mark such images as incompatible in this case?

**Comment by pvizeli** [comment]
Yes, with 143 we could do that and we do it. There is a debian based base image for Zero

**Comment by bauerj** [comment]
Awesome, thanks!
